name:                tutorial-zeromq
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/tutorial-zeromq#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - zeromq4-haskell
  - bytestring

default-extensions:
  - OverloadedStrings

executables:
  req-rep-server:
    source-dirs: src
    main: req_rep_server.hs
  req-rep-client:
    source-dirs: src
    main: req_rep_client.hs
  pub-sub-x-publisher:
    source-dirs: src
    main: pub_sub_x_publisher.hs
  pub-sub-x-subscriber:
    source-dirs: src
    main: pub_sub_x_subscriber.hs
  pub-sub-x-proxy:
    source-dirs: src
    main: pub_sub_x_proxy.hs
  req-rep-broker-client:
    source-dirs: src
    main: req_rep_broker_client.hs
  req-rep-broker-worker:
    source-dirs: src
    main: req_rep_broker_worker.hs
  req-rep-broker-broker:
    source-dirs: src
    main: req_rep_broker_broker.hs
